export const ROW_HEIGHT_PX = 44;
export const GANTT_HEADER_HEIGHT_PX = 44;
export const GANTT_TASK_BAR_HEIGHT_PX = 12;
export const GANTT_SUMMARY_BAR_HEIGHT_PX = 18;

export const SIDEBAR_COL_CONTROL_PX = 40;
export const SIDEBAR_COL_NAME_MIN_PX = 160;
export const SIDEBAR_COL_DURATION_PX = 70;
export const SIDEBAR_COL_START_PX = 90;
export const SIDEBAR_COL_END_PX = 90;

export const SIDEBAR_GRID_TEMPLATE_COLUMNS = `${SIDEBAR_COL_CONTROL_PX}px minmax(${SIDEBAR_COL_NAME_MIN_PX}px, 1fr) ${SIDEBAR_COL_DURATION_PX}px ${SIDEBAR_COL_START_PX}px ${SIDEBAR_COL_END_PX}px`;

export const SIDEBAR_GRID_MIN_WIDTH_PX =
  SIDEBAR_COL_CONTROL_PX +
  SIDEBAR_COL_NAME_MIN_PX +
  SIDEBAR_COL_DURATION_PX +
  SIDEBAR_COL_START_PX +
  SIDEBAR_COL_END_PX;
